Sdk connect
sonr-io/beam-react-native pull request #106
Opened 2022-07-22 21:23 UTC by hvhallmann

# Description

Include support to @sonr-io/react-native-ui-components instead of current Login flow

# Impact

- Impact: (Critical / High / Medium / Low)
  - Critical: Architectural changes / big refactorings / changes that touches core parts that can impact service availability
Needs to test the login process agagin

# How to test

Create one account and use .env Users to set matrix username and password

Is there any setup steps needed? no
Is there unit tests to cover the new changes? no

## 1. (Example) User should be able to see printed value

- Go to create account button
- Insert username and password, click next
- Insert matrixUsername and password.
- The system should login you directly if key match

2022-07-25 19:07 UTC, hvhallmann commented
please check if it is working in your local machine,
I have the feeling that one package is broken

2022-07-25 21:45 UTC, hvhallmann commented
The compiler is complaining about unmeet dependency with react-native-ui-components.
I tried to update ours, but got into a bunch of failures,
Let me know if this is required to merge

<img width="1162" alt="Screen Shot 2022-07-25 at 18 43 06" src="https://user-images.githubusercontent.com/7022648/180879226-7a0427f7-713f-4ff7-a83f-43fe3a7db69b.png">

2022-07-26 13:30 UTC, tgfassina requested changes
It authenticates nicely, but one feature that we broke was the session login, meaning that I have to log in every time I restart the app. If I log in and then restart the app, I shouldn't need to log in again.

Also this is probably the best time to delete the legacy login screen code.

2022-07-26 13:30 UTC, tgfassina commented on src/screens/Splash.tsx
> +  const onSuccessHandler = async (data: any) => {
Here we can use `SonrUserData` instead of `any`

2022-07-26 13:30 UTC, tgfassina commented on src/screens/Splash.tsx
> +  TouchableOpacity,
Can this go away? I think it's here only because we made the logo clickable, but that's no longer the case

2022-07-26 21:56 UTC, hvhallmann commented on src/screens/Splash.tsx
> +  TouchableOpacity,
yep, good point is no longer necessary

2022-07-26 21:56 UTC, hvhallmann commented on src/screens/Splash.tsx
> +  const onSuccessHandler = async (data: any) => {
good point!

2022-07-26 21:56 UTC, hvhallmann commented on src/screens/Splash.tsx
> +  const onSuccessHandler = async (data: any) => {
I forgot to save the session once the user logs in.
Now it is fixed

2022-07-27 12:25 UTC, tgfassina approved these changes
@hvhallmann really nice! Good to finally see this things working together 👏🏻

2022-07-27 12:25 UTC, merged